// <auto-generated />
namespace DLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addSumm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSumm));
        
        string IMigrationMetadata.Id
        {
            get { return "201908141043126_addSumm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
